[package]
name = "mariochao/ui-util"
description = "Fade tween the transparency of multiple instances."

version = "0.0.1"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/MarioChao/awesome-scripts-dump"

[dependencies]
